spring.application.name=webhook-service

# real time price data 
finnhub.api-key=d6nfo09r01qodk5vjlmgd6nfo09r01qodk5vjln0
finnhub.ws-url=wss://ws.finnhub.io
finnhub.symbols=AAPL,SPX,TSLA, DAX

# historical data
yahoo.finance-url=https://query1.finance.yahoo.com/v8/finance/chart/
